#!/usr/bin/sh

set -e

readonly config_dir="$HOME/.config/git"
force=false
target_dir="."

cp()
{
	${force} && command cp "$1" "$2" || command cp -i "$1" "$2"
}

while (( $# > 0 )); do
	case "$1" in 
		--force) 		force=true				;;
		--target-directory) 	target_dir="$2"	&& shift		;;
		*) 			printf 'invalid argument' && exit 1	;;
	esac
	shift
done

printf 'verifying node installation: '

node --version || \
	{ printf 'node not installed. downloading... ' && curl -s -X GET https://nodejs.org/dist/v12.16.2/node-v12.16.2-x64.msi > node.msi && printf 'starting installation\n' && cmd //c "msiexec.exe /i node.msi"; }

script_dir="$(dirname "$0")"

printf 'script directory: %s\n' "${script_dir}"

[ ! -d "${config_dir}" ] && { printf 'creating config directory: %s\n' "${config_dir}" && mkdir -p "${config_dir}"; } || printf 'config directory %s already exists\n' "${config_dir}"

printf 'copying %s to %s\n' "${script_dir}/commit-template" "${config_dir}"
cp "${script_dir}/commit-template" "${config_dir}"

printf 'setting up commit template %s\n' "${config_dir}/commit-template"
git --git-dir="${target_dir}/.git" config --local commit.template "${config_dir}/commit-template"

printf 'copying %s to %s\n' "${script_dir}/commit-msg" "${target_dir}/.git/hooks/"
cp "${script_dir}/commit-msg" "${target_dir}/.git/hooks/"

printf 'copying %s to %s\n' "${script_dir}/commitlint.config.js" "${target_dir}"
cp "${script_dir}/commitlint.config.js" "${target_dir}"

printf 'installing commitlint/cli, commitlint/config-conventional, conventional-changelog-conventionalcommits, and commitlint-plugin-cleanfeet\n'
[ ! -z "${target_dir}" ] && cd "${target_dir}"
npm install -g @commitlint/config-conventional @commitlint/cli commitlint-plugin-cleanfeet
npm install --save-dev conventional-changelog-conventionalcommits 

global_npm_dir="$(npm config get prefix | sed -e 's/\\/\//g' -e 's/://')"
[[ "${PATH,,}" != *"${global_npm_dir,,}"* ]] && printf 'updating .bashrc to include npm directory %s in path' "${global_npm_dir}" && printf 'PATH=${PATH:+${PATH}:}%s' "${global_npm_dir}" >> ~/.bashrc

printf 'all done!\n'

# vim: set filetype=sh:
